### ISSUE TITLE
Clean up the type usage

### ISSUE THREAD

**Issue by intrnl** [badlogic/skyview#6]
https://github.com/badlogic/skyview/blob/49bd06e2036b2d1d5008124033f0b4c88fdc2bc4/index.ts#L241-L315

these type definitions seems unnecessary because the API library [provides these definitions as well via `@intrnl/bluesky-client/atp-schema`](https://github.com/intrnl/bluesky-client#fiddling-with-at-protocol-schema)

as the API client is ESM-only, I'd recommend fixing the TypeScript configuration by setting `moduleResolution` to either `Node16` or `Bundler`, this should mean that you'd no longer need to put `// @ts-ignore` on the imports

I should probably attach this note to the README of the library for future users as well

**Comment by badlogic** [comment]
Needs a complete rewrite anyways some time :)
