### ISSUE TITLE
UTF-8 aware rich text

### ISSUE THREAD

**Issue by intrnl** [badlogic/skyview#7]
Bluesky's rich text works with UTF-8 indices for indicating which part of the text is part of a feature, the code currently in use in Skyview currently ignores this fact and uses the indices to slice text in UTF-16 (JavaScript) instead.

my recommendation would be to [follow the example I had provided here](https://github.com/intrnl/bluesky-client/blob/trunk/examples/richtext-segmenter.ts)

this makes sure that non-Latin posts are being rendered correctly

**Comment by intrnl** [comment]
Closing since it's now relying on the RichText API from `@atproto/api`

**Comment by badlogic** [comment]
Sorry didn't check the tracker before inplementing it :)

**Comment by intrnl** [comment]
It's all good, so long as the posts are being rendered correctly :)
