### ISSUE TITLE
Permit Unroll from a reply.

### ISSUE THREAD

**Issue by Br31zh** [badlogic/skyview#8]
On this thread: https://skyview.social/?url=https%3A%2F%2Fbsky.app%2Fprofile%2Ftristankamin.bsky.social%2Fpost%2F3kcprdojj7522&viewtype=unroll

You can see the thread up to 10/20. In the tree view you can see the others, but using Unroll on the URL of one of them still show the first 10 only.

It could be useful to allow starting the unroll from any message, instead of only the root of the tree.

**Comment by badlogic** [comment]
There doesn't appear to be more replies after the 10th post.

https://bsky.app/profile/did:plc:toudj53egawswz2ypw3zyn2u/post/3kcprhory272j
